SUPABASE__URL = "https://cdsmbjgvdgmckgjxzpqr.supabase.co"
SUPABASE__SUPABASE_SERVICE_KEY = "sb_secret_OXqK_MozyRWZ4HZIK_BoSg_hPbhUfWf"
PA_API_AUTOSTART = "1"
PA_API_APP = "provisioning.api:app"
PA_API_HOST = "127.0.0.1"
PA_API_PORT = "7000"
PA_API_RELOAD = "0"        # set "1" during API development
PA_API_SHOW_STATUS = "1"   # show tiny status in sidebar